#!/usr/bin/env python3
"""Metadata-only analysis of what the data_v1 split means (no model, no test scores).

Reports, per split: proposals/acceptances by edit kind, rejection reasons, the
orbit-ownership filter's keep rate for each op type, accepted op types, orbits
owned and used, binding-necessary share and attribute marginals (with total
variation distance to train). Also fixes and describes the paired-comparison
panel (train: first 512 train groups; dev: dev groups 32..159, excluding the 32
groups already scored by pixel_baseline_v1).
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from itertools import combinations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from bindcomp import vocab  # noqa: E402
from bindcomp.dataset import SPLITS, build_dataset, dataset_hash, orbit_owner  # noqa: E402
from bindcomp.evaluate import binding_necessary  # noqa: E402
from bindcomp.manifest import RunRecorder, sha256_json, utc_stamp  # noqa: E402

ORBIT_DEFINITION = (
    "Edit orbit of a scene = orbit under the group generated by binding edits (transpositions of one "
    "attribute type between two objects) and relation edits (transpositions of slots), with shapes attached "
    "to object identities; ignoring validity of intermediate scenes this is the set of valid scenes with the "
    "same multisets of shapes, colours and materials (key = Scene.content_key). Attribute and object edits "
    "change these multisets and therefore map a scene to a different orbit."
)


def all_orbit_keys():
    triples = [(s, c, m) for s in vocab.SHAPES for c in vocab.COLORS for m in vocab.MATERIALS]
    keys = set()
    for combo in combinations(triples, 3):
        keys.add(tuple(tuple(sorted(t[i] for t in combo)) for i in range(3)))
    return keys


def marginals(groups):
    c = {f: Counter() for f in ("shape", "color", "material")}
    for g in groups:
        for s in g.scenes:
            for o in s.objects:
                for f in c:
                    c[f][o.get(f)] += 1
    return {f: {k: v / sum(cnt.values()) for k, v in sorted(cnt.items())} for f, cnt in c.items()}


def tv(p, q):
    keys = set(p) | set(q)
    return 0.5 * sum(abs(p.get(k, 0.0) - q.get(k, 0.0)) for k in keys)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/paired_v1.json")
    args = ap.parse_args()
    pcfg = json.loads((ROOT / args.config).read_text())
    dcfg = json.loads((ROOT / pcfg["data_config"]).read_text())
    out = ROOT / "runs" / f"split_semantics_v1_{utc_stamp()}"
    with RunRecorder("split_semantics_v1", out) as rec:
        rec.extra.update(config_sha256=sha256_json(pcfg), data_config_sha256=sha256_json(dcfg))
        trace = {}
        ds, stats = build_dataset(dcfg, trace=trace)
        rec.extra["data_sha256"] = dataset_hash(ds)
        keys = all_orbit_keys()
        owned = Counter(orbit_owner(k, dcfg) for k in keys)
        train_marg = marginals(ds["train"])
        res = {"orbit_definition": ORBIT_DEFINITION, "n_orbits_total": len(keys),
               "test_model_scores": "NOT OPENED (metadata only)", "splits": {}}
        for split in SPLITS:
            gs, t = ds[split], trace[split]
            f = t["filter"]
            content = [k for k in f if k[0] == "applicable" and k[1] in ("replace_attr", "replace_shape")]
            appl_c = sum(f[k] for k in content)
            kept_c = sum(f[("kept",) + k[1:]] for k in content)
            filt = {f"{k[1]}:{k[2]}": {"applicable": f[k], "kept": f[("kept",) + k[1:]],
                                       "keep_rate": f[("kept",) + k[1:]] / f[k] if f[k] else None}
                    for k in sorted(f) if k[0] == "applicable"}
            m = marginals(gs)
            res["splits"][split] = {
                "n_groups": len(gs), "attempts": stats[split]["attempts"],
                "accept_rate": len(gs) / stats[split]["attempts"],
                "proposals_by_kind": dict(t["proposals"]), "accepted_by_kind": dict(t["accepted"]),
                "accept_rate_by_kind": {k: t["accepted"][k] / t["proposals"][k] for k in t["proposals"]},
                "rejects_by_kind_reason": {f"{k}|{r}": v for (k, r), v in sorted(t["rejects_by_kind"].items())},
                "orbit_filter_by_op": filt,
                "content_edit_filter_keep_rate": kept_c / appl_c if appl_c else None,
                "accepted_ops": {f"{a}:{b}": v for (a, b), v in sorted(t["accepted_ops"].items())},
                "n_orbits_owned": owned[split], "n_orbits_used": len({s.content_key() for g in gs for s in g.scenes}),
                "binding_necessary_fraction": sum(binding_necessary(g.kind_label) for g in gs) / len(gs),
                "marginals": m, "tv_to_train": {fld: tv(m[fld], train_marg[fld]) for fld in m},
            }
            rec.log(f"{split}: {len(gs)} groups / {stats[split]['attempts']} attempts, orbits owned "
                    f"{owned[split]} used {res['splits'][split]['n_orbits_used']}, content filter keep "
                    f"{res['splits'][split]['content_edit_filter_keep_rate']}, BN "
                    f"{res['splits'][split]['binding_necessary_fraction']:.3f}")
        res["orbits_unowned"] = owned[None]

        # ---- fixed paired-comparison panel ------------------------------------
        P = pcfg["panel"]
        train = ds["train"][P["train"]["start"]:P["train"]["start"] + P["train"]["n_groups"]]
        dev = ds["dev"][P["dev"]["start"]:P["dev"]["start"] + P["dev"]["n_groups"]]
        panel = {}
        for name, gs, split in (("train", train, "train"), ("dev", dev, "dev")):
            ok = all(orbit_owner(s.content_key(), dcfg) == split for g in gs for s in g.scenes)
            panel[name] = {"n_groups": len(gs), "gids_first_last": [gs[0].gid, gs[-1].gid],
                           "n_orbits": len({s.content_key() for g in gs for s in g.scenes}),
                           "kinds": dict(Counter(g.kind_label for g in gs)),
                           "binding_necessary_fraction": sum(binding_necessary(g.kind_label) for g in gs) / len(gs),
                           "all_orbits_owned_by_split": ok, "marginals": marginals(gs)}
        panel["dev"]["excluded_previously_scored"] = P["dev"]["start"]
        panel["orbit_overlap_train_dev"] = len({s.content_key() for g in train for s in g.scenes}
                                               & {s.content_key() for g in dev for s in g.scenes})
        panel["gids_sha256"] = sha256_json({"train": [g.gid for g in train], "dev": [g.gid for g in dev]})
        res["panel"] = panel
        rec.log(f"panel: train {panel['train']['n_groups']} groups / {panel['train']['n_orbits']} orbits, dev "
                f"{panel['dev']['n_groups']} groups / {panel['dev']['n_orbits']} orbits, overlap "
                f"{panel['orbit_overlap_train_dev']}")
        (out / "split_semantics.json").write_text(json.dumps(res, indent=1, default=str))
        rec.extra["panel_gids_sha256"] = panel["gids_sha256"]
    print(out)


if __name__ == "__main__":
    main()
